name= "Saquib Bin Halim"

print(name.upper()) #for Captila Letters....
print(name) #for displaying the name as it is...

print(name.lower()) #forr displaying the letters in smaller form...

print(name.find('S')) # finding the STing searching for substrings..
#Every strings starts from #0...
print(name.replace("Saquib Bin Halim" , "Ironman")) #for replacing the name with some other name...
print('m' in name) #Used for Boolean Expression...